#!/bin/sh

if [[ ! $# -eq 1 ]] ; then ## || $1 != "on" && $1 != "off" && $1 != "1" && $1 != "0" ]] ; then
    echo "Usage: redled [on | 1 | off | 0]"
    exit 0
fi


if [[ $1 != "on" && $1 != "off" && $1 != "1" && $1 != "0" ]] ; then
    echo "Usage: redled [on | 1 | off | 0]"
    exit 0
fi

# if the red LED gpio does not exit, die.
if [[ ! -d /sys/class/leds/ledB\:red/ ]] ; then
    echo "Error:  The LED sysfs directory doesn't exist!"
    exit 0
fi

# poke the gpio
if [[ $1 == "on" || $1 == "1" ]] ; then
    echo 1 > /sys/class/leds/ledB\:red/brightness
elif [[ $1 == "off" || $1 == "0" ]] ; then
    echo 0 > /sys/class/leds/ledB\:red/brightness
fi
